### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by ghost**
This is the initial Italian translation for Lightbulb Paranoid Android
application.

Filippo Favaro faavaro@gmail.com

### CODE REVIEW

**Comment by kaluoshi** [comment]
I say "La fotocamera del tuo dispositivo non è provvista di flash LED. Lo schermo diventerà bianco in alternativa."
Update it and i'll merge :)

**Comment by ghost** [comment]
I've updated it

**Comment by evan-a-a** [comment]
Rebase your commits into one by doing git rebase -i HEAD~2.

**Comment by kaluoshi** [comment]
Yea rebase them into one and i'll merge.

**Comment by ghost** [comment]
Here is the updated version in one commit

https://github.com/filippofavaro/android_packages_apps_Lightbulb/commit/d8ec8e221b7ac014c062730a6cf85681961c4173

**Comment by kaluoshi** [comment]
Ok i'm closing it picked last one manually :) https://github.com/AOSPA/android_packages_apps_Lightbulb/commit/fc7fec6b9b696e92ac1e59936d46d33c2d9e24e1

**Pull request closed without merging**
